sa

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,111 +1,49 @@
 version: 2.1
 
 commands:
-  install_awscli:
-    description: Install AWS CLI v2
-    steps:
-      - run:
-          name: Install aws cli v2
-          command: |
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-  install_ansible:
-    description: Install Ansible v2
-    steps:
-      - run:
-          name: Install Ansible v2
-          command: |
-            sudo apt update
-            sudo apt install --yes software-properties-common
-            sudo add-apt-repository --yes --update ppa:ansible/ansible
-            sudo apt install ansible --yes
-
-  install_nodejs:
-    description: Install nodejs
-    steps:
-      - run:
-          name: Install nodejs
-          command: |
-            sudo apt update
-            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt-get install -y nodejs
-            sudo npm install -g n
-            sudo n 13.8.0
-
   destroy-environment:
-    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.   
     parameters:
-      workflowID:
+      workflow_id:
         type: string
         default: ${CIRCLE_WORKFLOW_ID:0:7}
     steps:
       - run:
-          name: Echo workflow ID that is going be be destroyed
-          when: on_fail
-          command: echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"
-      - run:
-          name: Destroy backend stack
+          name: Destroy environments
           when: on_fail
           command: |
-            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflowID >>
-            aws s3 rm arn:aws:s3:::udapeople-<< parameters.workflowID >> --recursive
-            aws s3 rb arn:aws:s3:::udapeople-<< parameters.workflowID >> --force
-      - run:
-          name: Destroy frontend stack
-          when: on_fail
-          command: |
-            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflowID >>
-
-
-  create-dotenv-file:
-    description: Create .env file
-    steps:
-      - run:
-          name: Add env vars to .env file
-          command: |
-            echo ENVIRONMENT=$ENVIRONMENT > "./backend/.env"
-            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> "./backend/.env"
-            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> "./backend/.env"
-            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> "./backend/.env"
-            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> "./backend/.env"
-            echo TYPEORM_HOST=$TYPEORM_HOST >> "./backend/.env"
-            echo TYPEORM_PORT=$TYPEORM_PORT >> "./backend/.env"
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "./backend/.env"
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "./backend/.env"
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "./backend/.env"
-#            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-#            unzip awscliv2.zip
-#            sudo ./aws/install
-#            aws s3 rm s3://udapeople-<<parameters.id>> --recursive
-#            aws cloudformation delete-stack \
-#              --stack-name "udapeople-frontend-<<parameters.id>>"
-#            aws cloudformation delete-stack \
-#              --stack-name "udapeople-backend-<<parameters.id>>"
-
+            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
+            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
+    
   revert-migrations:
-    description: Revert the last migration if successfully run in the current workflow.
+    description: Revert the last migration 
+    parameters:
+      workflow_id:
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string     
     steps:
       - run:
           name: Revert migrations
           when: on_fail
           command: |
-            SUCCESS=$(curl https://kvdb.io/YHfkL8imZwJhHwV2UGVznq/migration)
-            if (( $SUCCESS == 1 ));
+            SUCCESS=$(curl --insecure  https://kvdb.io/YHfkL8imZwJhHaawV2UGVznq/migration_<< parameters.workflow_id >>)
+            if(( $SUCCESS==1 )); 
             then
               cd ~/project/backend
               npm install
-              npm run migrations:revert
+              npm run migration:revert
+              exit 1
             fi
-            
 jobs:
+#Job to build the front-end of the application.
   build-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
           name: Build front-end
           command: |
@@ -114,99 +52,102 @@ jobs:
             npm run build
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-deps
+          key: frontend-build
 
+
+#Job to build the backend
   build-backend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
-#      - restore_cache:
-#          keys: [backend-deps]
-      - create-dotenv-file
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: Back-end build
           command: |
             cd backend
-            echo "1"
-            sudo npm install typescript -g
-            echo "1-1"
-            sudo npm install
-            echo "2"
-            sudo npm run build
-            echo "3"
+            npm install
+            npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-deps
-
+          key: backend-build
+  
+  #Run unit tests on frontend
   test-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
-          name: front-end unit test
+          name: Unit tests frontend
           command: |
             cd frontend
-            sudo npm install
-            sudo npm test
-                
+            npm install
+            npm run test
+      
+ #Run unit tests on backend               
   test-backend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-deps]
+          keys: [backend-build]
       - run:
-          name: Back-end unit test
+          name: Unit tests backend
           command: |
             cd backend
-            sudo npm install
-            sudo npm test --updateSnapshot
-            
+            npm install
+            npm run test
+  
+#Scan frontend for vulnerabilities
   scan-frontend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
-          name: front-end scan
+          name: Code analysis frontend
           command: |
             cd frontend
-            npm install --save
-            exit 0
+            npm install
+            #npm install oauth-sign@^0.9.0
+            #fix vulnerabilities
             npm audit fix --audit-level=critical --force
             npm audit fix --force
             npm audit --audit-level=critical
-
+#Scan backend for vulnerabilities
   scan-backend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-deps]
+          keys: [backend-build]
       - run:
-          name: Back-end scan
+          name: Code analysis backend
           command: |
             cd backend
-            sudo npm install
-            sudo npm audit fix --audit-level=critical --force
-            sudo npm audit fix --audit-level=critical --force
-            sudo npm audit --audit-level=critical
-
-
+            npm install
+            #npm install oauth-sign@^0.9.0
+            #fix vulnerabilities
+            npm audit fix --audit-level=critical --force
+            npm audit fix --force
+            npm audit --audit-level=critical
+#Create Infrastructure IAC  
   deploy-infrastructure:
     docker:
-      - image: cimg/base:stable
+      - image: amazon/aws-cli
     steps:
       - checkout
-      - install_awscli
+      - run: 
+          name: Install Tar and Gzip
+          command: yum install -y tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
@@ -214,7 +155,7 @@ jobs:
               --template-file .circleci/files/backend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
       - run:
           name: Ensure front-end infrastructure exist
           command: |
@@ -222,157 +163,156 @@ jobs:
               --template-file .circleci/files/frontend.yml \
               --tags project=udapeople \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            echo $BACKEND_PUBLIC_IP >> .circleci/ansible/inventory.txt
-            cat .circleci/ansible/inventory.txt
+            aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> ~/project/.circleci/ansible/inventory.txt
+            
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-#      - destroy-environment
+      #Destroy environment if job fails 
+      - destroy-environment
 
+#Configure infrastructure using Ansible
   configure-infrastructure:
     docker:
-      - image: cimg/base:stable
+      - image: python:3.7-alpine3.11
+
     steps:
       - checkout
-      - install_awscli
+      
       - add_ssh_keys:
-          fingerprints: ["67:0a:4f:1d:2b:ff:d0:b1:59:d1:24:75:b0:06:a7:02"]
-      - attach_workspace:
-          at: /tmp/workspace
+          fingerprints: ["67:0a:4f:1d:2b:ff:d0:b1:59:d1:24:75:b0:06:a7:02"] 
+      
+      - attach_workspace: 
+          at: ~/
+     
       - run:
           name: Install dependencies
           command: |
-            sudo apt-add-repository ppa:ansible/ansible
-            sudo apt update
-            sudo apt install ansible
+            apk add --update ansible
       - run:
           name: Configure server
-          working_directory: .circleci/ansible/
           command: |
-            echo "[web]" > inventory.txt
-            BACKEND_PUBLIC_IF=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            echo $BACKEND_PUBLIC_IF >> inventory.txt
-            cat inventory.txt
+            cd .circleci/ansible
             ansible-playbook -i inventory.txt configure-server.yml
+      
+      #Destroy environment if job fails 
+      - destroy-environment
 
+#Initiate migrations
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - install_awscli
-      - create-dotenv-file
-      - attach_workspace:
-            at: ~/
       - run:
-          name: Prepare NodeJS
+          name: Run migrations
           command: |
             cd backend
-            export TYPEORM_MIGRATIONS_DIR=/home/circleci/project/backend/src/migrations
-            export TYPEORM_ENTITIES=/home/circleci/project/backend/src/modules/domain/**/*.entity.ts
-            export TYPEORM_MIGRATIONS=/home/circleci/project/backend/src/migrations/*.ts
-            sudo npm cache clean --force
-            sudo rm -rf node_modules
-            sudo npm install
-            cat .env
+            npm install
+            #Run and save the migration output
             npm run migrations > migrations_dump.txt
-            cat migrations_dump.txt
-            pwd
-            if grep -q "has been executed successfully." migrations_dump.txt
-            then
-                curl --insecure https://kvdb.io/YHfkL8imZwJhHaawV2UGVznq/migration_${CIRCLE_WORKFLOW_ID:0:7} -d '1'
-            fi
-      - revert-migrations
-
-     # Here's where you will add some code to rollback on failure  1    
-
-  deploy-frontend:
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - restore_cache:
-          keys: [frontend-deps]
       - run:
           name: Install dependencies
           command: |
-            cd frontend
-            npm install
+            sudo apt-get update -y && sudo apt-get install -y python3 \
+            python3-pip python3-setuptools groff less -y && sudo pip3 install --upgrade pip \
+            && sudo apt-get clean && sudo apt-get install curl
+      
+      - run:
+          name: Install awscli
+          command: |
+            pip3 --no-cache-dir install --upgrade awscli
+      - run:
+          name: Send migration results to kvdb
+          command: |
+              if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+                  curl https://kvdb.io/YHfkL8imZwJhHaawV2UGVznq/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              fi
+      #Destroy environment and revert migrations if job fails 
+      - destroy-environment
+      - revert-migrations
+  
+#Deploy App Frontend
+  deploy-frontend:
+    docker:
+      - image: circleci/node:13.8.0
+
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - attach_workspace: 
+          at: ~/
+        
+      - run: 
+          name: Install Dependencies
+          command: |
+            sudo apt-get update && sudo apt-get install -y tar \
+            && sudo apt-get install -y awscli
       - run:
           name: Get backend url
           command: |
-            BACKEND_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            export API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
             cat frontend/.env
+        
       - run:
           name: Deploy frontend objects
           command: |
             cd frontend
+            npm install
             npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 ls
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-            echo "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
-      # Here's where you will add some code to rollback on failure      
-                    
+      #Destroy environment and revert migrations if job fails 
+      - destroy-environment
+      - revert-migrations
+
+#Deploy App Backend
   deploy-backend:
     docker:
-      - image: cimg/node:13.8.0
+      - image: python:3.7-alpine3.11
+    
     steps:
       - checkout
-      - install_awscli
-      - install_nodejs
-      - install_ansible
+
+      - restore_cache:
+          keys: [backend-build]
+
       - add_ssh_keys:
-          fingerprints: ["67:0a:4f:1d:2b:ff:d0:b1:59:d1:24:75:b0:06:a7:02"]
+          fingerprints: ["67:0a:4f:1d:2b:ff:d0:b1:59:d1:24:75:b0:06:a7:02"] 
+      
+      - attach_workspace: 
+          at: ~/
+
       - run:
           name: Install dependencies
           command: |
-            cd backend
-            npm install
-      - run:
-          name: Package backend
-          command: |
-            cd backend
-            sudo npm install typescript -g
-            sudo npm install
-            sudo npm run build
-            tar -czf artifact.tar.gz dist/* package*
-            cd ..
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+            apk add --update tar gzip ansible openssh nodejs npm 
+            pip3 install awscli 
       - run:
           name: Deploy backend
           command: |
-            export TYPEORM_MIGRATIONS_DIR=/home/circleci/project/backend/src/migrations
-            export TYPEORM_ENTITIES=/home/circleci/project/backend/src/modules/domain/**/*.entity.ts
-            export TYPEORM_MIGRATIONS=/home/circleci/project/backend/src/migrations/*.ts
-            cd .circleci/ansible/
-            echo "[web]" > inventory.txt
-            BACKEND_PUBLIC_IF=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            echo $BACKEND_PUBLIC_IF >> inventory.txt
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz . 
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
-            sudo sed -i 's/host_key_checking = True/host_key_checking = False/g' /etc/ansible/ansible.cfg
-            sudo sed -i 's/host_key_checking=True/host_key_checking = False/g' /etc/ansible/ansible.cfg
-            ANSIBLE_HOST_KEY_CHECKING=False
-            sudo ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.txt deploy-backend.yml
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      #Destroy environment and revert migrations if job fails.
       - destroy-environment
       - revert-migrations
 
